# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('console/index.html', 'console'),
        ('console/css/*.css', 'console/css'),
        ('console/js/*.js', 'console/js'),
        ('alphabase.js', '.'),
        ('config.py', '.'),
        ('models.py', '.'),
        ('security_rules.py', '.'),
        ('query_system.py', '.'),
        ('file_storage.py', '.'),
        ('mqtt_manager.py', '.'),
        ('websocket_manager.py', '.'),
        ('requirements.txt', '.'),
        ('README.md', '.'),
        ('INSTALL.txt', '.'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'paho.mqtt.client',
        'passlib.handlers.argon2',
        'config',
        'models',
        'security_rules',
        'query_system',
        'file_storage',
        'mqtt_manager',
        'websocket_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AlphaBase',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AlphaBase',
)